### ISSUE TITLE
RuntimeError: storage has wrong size

### ISSUE THREAD

**Issue by Johnzu-2019** [v-iashin/BMT#10] opened 2020-10-14 08:42 UTC
I got this in the prediction section
`(bmt) root@ABC001:/data/zuyuehan/project/BMT# python ./sample/single_video_prediction.py     --prop_generator_model_path ./sample/best_prop_model.pt     --pretrained_cap_model_path ./sample/best_cap_model.pt     --vggish_features_path ./test/pandemic_vggish.npy     --rgb_features_path ./test/pandemic_rgb.npy     --flow_features_path ./test/pandemic_flow.npy     --duration_in_secs 99     --device_id 0     --max_prop_per_vid 100     --nms_tiou_thresh 0.4
Contructing caption_iterator for "train" phase
Using vanilla Generator
initialization: xavier
Glove emb of the same size as d_model_caps
Traceback (most recent call last):
  File "./sample/single_video_prediction.py", line 281, in <module>
    args.device_id, args.prop_generator_model_path, args.pretrained_cap_model_path, args.max_prop_per_vid
  File "./sample/single_video_prediction.py", line 94, in load_prop_model
    checkpoint = torch.load(prop_generator_model_path, map_location='cpu')
  File "/root/anaconda3/envs/bmt/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/bmt/lib/python3.7/site-packages/torch/serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 0 got 512
`
I need your help, and I'd appreciate it if you could help me.

**Comment by v-iashin** [comment] 2020-10-14 11:15
Hi,

Thanks for reporting. Does it work with the example video from README?

**Comment by Johnzu-2019** [comment] 2020-10-14 11:23
> 你好
> 
> 感谢您的举报。它可以与README的示例视频一起使用吗？

Yes, I used the README video and got the same error.

**Comment by v-iashin** [comment] 2020-10-14 12:17
I am afraid I cannot reproduce your error on my side.

I would suggest checking the md5 sums of the models you are trying to load:
```bash
md5sum ./sample/best_prop_model.pt
5f8b20826b09eadd41b7a5be662c198b  ./sample/best_prop_model.pt

md5sum ./sample/best_cap_model.pt
7b4d48cd77ec49a027a4a1abc6867ee7  ./sample/best_cap_model.pt
```

Are you using distributed training of some sort?

**Comment by Johnzu-2019** [comment] 2020-10-15 08:53
> 恐怕我无法重现您的错误。
> 
> 我建议检查您要加载的模型的md5总和：
> 
> ```shell
> md5sum ./sample/best_prop_model.pt
> 5f8b20826b09eadd41b7a5be662c198b ./sample/best_prop_model.pt
> 
> md5sum ./sample/best_cap_model.pt
> 7b4d48cd77ec49a027a4a1abc6867ee7 ./sample/best_cap_model.pt
> ```
> 
> 您是否正在使用某种形式的分布式培训？



> I am afraid I cannot reproduce your error on my side.
> 
> I would suggest checking the md5 sums of the models you are trying to load:
> 
> ```shell
> md5sum ./sample/best_prop_model.pt
> 5f8b20826b09eadd41b7a5be662c198b  ./sample/best_prop_model.pt
> 
> md5sum ./sample/best_cap_model.pt
> 7b4d48cd77ec49a027a4a1abc6867ee7  ./sample/best_cap_model.pt
> ```
> 
> Are you using distributed training of some sort?

Thank you very much indeed. According to your suggestion, I found that the MD5 code of the.pt file I uploaded to the server was wrong. After I re-uploaded the correct.PT file, I ran it successfully.You are such a good man. You have been very helpful to me as a beginner.

**Comment by v-iashin** [comment] 2020-10-15 08:58
No problem. Good luck with your endeavors!

Closing this.

**Closed by v-iashin** 2020-10-15 08:58 UTC
